services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    restart: always
    user: root
    ports:
      - "8080:8080"  # Jenkins UI port
      - "50000:50000"  # For Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home  # Persistent storage for Jenkins
      - /var/run/docker.sock:/var/run/docker.sock  # To run Docker inside Jenkins

volumes:
  jenkins_home:
    driver: local
